name: BaseRock CLI Tests

on: [ workflow_dispatch, push ]

permissions:
  contents: read

jobs:
  baseRock-cli-tests:
    runs-on: ubuntu-latest
    steps:
      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc      
          sudo apt-get remove google-chrome-stable
          sudo apt-get autoremove -y
          sudo apt-get autoclean -y
          docker rmi $(docker image ls -aq)
          df -h

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #- name: Google Auth
      #  if: ${{ github.actor != 'dependabot[bot]' }}
      #  uses: 'google-github-actions/auth@v0'
     #   with:
     #     credentials_json: '${{ secrets.GCP_PROD_IMAGE_UPLOAD_SERVICE_ACCOUNT }}'

      - name: Set up Gcloud
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Remove any existing local file
        run: rm -f baserock-cli.jar

      - name: Download BaseRock cli test generation and execution jar
        run: gsutil -o "GSUtil:parallel_thread_count=1" -o "GSUtil:parallel_process_count=1" cp gs://ai-sapient-cli/baserock-cli-20241111.3.jar baserock-cli.jar

      - name: Execute all tests for the module
        env:
          SOURCE_BRANCH: master
          TARGET_BRANCH: master
          RUN_TEST_FOR_ALL_CLASSES: true
          environmentType: dev
          SAPIENT_CLI_API_KEY: ${{ secrets.SAPIENT_CLI_API_KEY_GITHUB_DEV }}
        run: mvn clean test

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/jacocoHtml
